
name: Build PySOEM sdist and wheels and upload them to TestPyPI

# This workflow can only be manually triggered using the UI.
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pysoem
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/